name: Build MyPet

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: 0
      JAR_FILE_NAME: ""
      NMS_VERSIONS: ""
      PROJECT_VERSION: ""

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'microsoft'

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-${{ hashFiles('**/install_dependencies.sh') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Dependencies
        run: ./install_dependencies.sh

      - name: Set build number
        env:
          NUM: ${{ github.run_number }}
        run: |
          echo "BUILD_NUMBER=$(($NUM+1592))" >> $GITHUB_ENV

      - name: Get jar file name
        run: |
          echo "JAR_FILE_NAME=$(find ./target -maxdepth 1 -regex '.*/MyPet-3\.[0-9]+-?S?N?A?P?S?H?O?T?\.jar' | sed -e 's/"//g')" >> $GITHUB_ENV

      - name: Get supported NMS versions
        run: |
          cd modules/MyPet
          echo NMS_VERSIONS=$(mvn help:evaluate -Dexpression=bukkit.packets -q -DforceStdout)
          echo NMS_VERSIONS=$(mvn help:evaluate -Dexpression=bukkit.packets -q -DforceStdout) >> $GITHUB_ENV

      - name: Get project version
        run: |
          cd modules/MyPet
          echo PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_ENV

      - name: List files in build/libs
        run: ls -la target

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: target/*.jar  # Update this path as needed
     
